version: '3'

services:
  frontend:
    image: kiritantakechi/admin:latest
    restart: always
    ports:
      - 3210:3210
    networks:
      net:
        ipv4_address: 172.16.3.2

networks:
  net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.3.0/24
